# name of the software
name: Jekyll Bootstrap Doc
# current version of the software
version: 1.0.1
# url of the download button
downloadUrl: https://github.com/mistic100/jekyll-bootstrap-doc
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/nniiicc

# list of additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/nniiicc
  - title: Issues
    url: https://github.com/

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# github buttons
githubButton:
  user: nniiicc
  repo: 

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: nniiicc

# facebook buttons
facebook:
  enabled: false    
  profileUrl:

# To render better tables
markdown: kramdown

# google analytics
analytics:
  account:
  domain:


# DON'T MODIFY
pygments: true
highlight: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
